# Generated by Django 3.0.3 on 2020-03-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200308_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
